// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Configuration.Countries;
using KozshTheMovieDbApi.v3.Configuration.Jobs;
using KozshTheMovieDbApi.v3.Configuration.Languages;
using KozshTheMovieDbApi.v3.Configuration.Primary_translations;
using KozshTheMovieDbApi.v3.Configuration.Timezones;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Configuration
{
    /// <summary>
    /// Builds and executes requests for operations under \3\configuration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigurationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The countries property</summary>
        public global::KozshTheMovieDbApi.v3.Configuration.Countries.CountriesRequestBuilder Countries
        {
            get => new global::KozshTheMovieDbApi.v3.Configuration.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::KozshTheMovieDbApi.v3.Configuration.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::KozshTheMovieDbApi.v3.Configuration.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The languages property</summary>
        public global::KozshTheMovieDbApi.v3.Configuration.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::KozshTheMovieDbApi.v3.Configuration.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The primary_translations property</summary>
        public global::KozshTheMovieDbApi.v3.Configuration.Primary_translations.Primary_translationsRequestBuilder Primary_translations
        {
            get => new global::KozshTheMovieDbApi.v3.Configuration.Primary_translations.Primary_translationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timezones property</summary>
        public global::KozshTheMovieDbApi.v3.Configuration.Timezones.TimezonesRequestBuilder Timezones
        {
            get => new global::KozshTheMovieDbApi.v3.Configuration.Timezones.TimezonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ConfigurationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigurationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/configuration", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ConfigurationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigurationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/configuration", rawUrl)
        {
        }
        /// <summary>
        /// Query the API configuration details.
        /// </summary>
        /// <returns>A <see cref="ConfigurationGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Configuration.ConfigurationGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Configuration.ConfigurationGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Configuration.ConfigurationGetResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Configuration.ConfigurationGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Query the API configuration details.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="ConfigurationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Configuration.ConfigurationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Configuration.ConfigurationRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
