// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states
{
    /// <summary>
    /// Builds and executes requests for operations under \3\tv\{series_id}\season\{season_number}\episode\{episode_number}\account_states
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Account_statesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="Account_statesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Account_statesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states{?guest_session_id*,session_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="Account_statesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Account_statesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states{?guest_session_id*,session_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the rating, watchlist and favourite status.
        /// </summary>
        /// <returns>A <see cref="Account_statesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesGetResponse?> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesRequestBuilder.Account_statesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesGetResponse> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesRequestBuilder.Account_statesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesGetResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the rating, watchlist and favourite status.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesRequestBuilder.Account_statesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesRequestBuilder.Account_statesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="Account_statesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Tv.Item.Season.Item.Episode.Item.Account_states.Account_statesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the rating, watchlist and favourite status.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Account_statesRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("guest_session_id")]
            public string? GuestSessionId { get; set; }
#nullable restore
#else
            [QueryParameter("guest_session_id")]
            public string GuestSessionId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("session_id")]
            public string? SessionId { get; set; }
#nullable restore
#else
            [QueryParameter("session_id")]
            public string SessionId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
