// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KozshTheMovieDbApi.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::KozshTheMovieDbApi.Models.FindMovieResult"/>, <see cref="global::KozshTheMovieDbApi.Models.FindTvResult"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FindKnownForItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::KozshTheMovieDbApi.Models.FindMovieResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KozshTheMovieDbApi.Models.FindMovieResult? FindMovieResult { get; set; }
#nullable restore
#else
        public global::KozshTheMovieDbApi.Models.FindMovieResult FindMovieResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::KozshTheMovieDbApi.Models.FindTvResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KozshTheMovieDbApi.Models.FindTvResult? FindTvResult { get; set; }
#nullable restore
#else
        public global::KozshTheMovieDbApi.Models.FindTvResult FindTvResult { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KozshTheMovieDbApi.Models.FindKnownForItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KozshTheMovieDbApi.Models.FindKnownForItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("media_type")?.GetStringValue();
            var result = new global::KozshTheMovieDbApi.Models.FindKnownForItem();
            if("movie".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FindMovieResult = new global::KozshTheMovieDbApi.Models.FindMovieResult();
            }
            else if("tv".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FindTvResult = new global::KozshTheMovieDbApi.Models.FindTvResult();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(FindMovieResult != null)
            {
                return FindMovieResult.GetFieldDeserializers();
            }
            else if(FindTvResult != null)
            {
                return FindTvResult.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(FindMovieResult != null)
            {
                writer.WriteObjectValue<global::KozshTheMovieDbApi.Models.FindMovieResult>(null, FindMovieResult);
            }
            else if(FindTvResult != null)
            {
                writer.WriteObjectValue<global::KozshTheMovieDbApi.Models.FindTvResult>(null, FindTvResult);
            }
        }
    }
}
#pragma warning restore CS0618
