// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KozshTheMovieDbApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FindGenericMediaBase_media_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "movie")]
        #pragma warning disable CS1591
        Movie,
        #pragma warning restore CS1591
        [EnumMember(Value = "tv")]
        #pragma warning disable CS1591
        Tv,
        #pragma warning restore CS1591
    }
}
