// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Authentication.Token.New;
using KozshTheMovieDbApi.v3.Authentication.Token.Validate_with_login;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KozshTheMovieDbApi.v3.Authentication.Token
{
    /// <summary>
    /// Builds and executes requests for operations under \3\authentication\token
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TokenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The new property</summary>
        public global::KozshTheMovieDbApi.v3.Authentication.Token.New.NewRequestBuilder New
        {
            get => new global::KozshTheMovieDbApi.v3.Authentication.Token.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validate_with_login property</summary>
        public global::KozshTheMovieDbApi.v3.Authentication.Token.Validate_with_login.Validate_with_loginRequestBuilder Validate_with_login
        {
            get => new global::KozshTheMovieDbApi.v3.Authentication.Token.Validate_with_login.Validate_with_loginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/authentication/token", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/authentication/token", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
