// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Movie.Item.Account_states;
using KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles;
using KozshTheMovieDbApi.v3.Movie.Item.Changes;
using KozshTheMovieDbApi.v3.Movie.Item.Credits;
using KozshTheMovieDbApi.v3.Movie.Item.External_ids;
using KozshTheMovieDbApi.v3.Movie.Item.Images;
using KozshTheMovieDbApi.v3.Movie.Item.Keywords;
using KozshTheMovieDbApi.v3.Movie.Item.Lists;
using KozshTheMovieDbApi.v3.Movie.Item.Rating;
using KozshTheMovieDbApi.v3.Movie.Item.Recommendations;
using KozshTheMovieDbApi.v3.Movie.Item.Release_dates;
using KozshTheMovieDbApi.v3.Movie.Item.Reviews;
using KozshTheMovieDbApi.v3.Movie.Item.Similar;
using KozshTheMovieDbApi.v3.Movie.Item.Translations;
using KozshTheMovieDbApi.v3.Movie.Item.Videos;
using KozshTheMovieDbApi.v3.Movie.Item.Watch;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Movie.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \3\movie\{movie_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMovie_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The account_states property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Account_states.Account_statesRequestBuilder Account_states
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Account_states.Account_statesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The alternative_titles property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder Alternative_titles
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The changes property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Changes.ChangesRequestBuilder Changes
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Changes.ChangesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credits property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Credits.CreditsRequestBuilder Credits
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Credits.CreditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The external_ids property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.External_ids.External_idsRequestBuilder External_ids
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.External_ids.External_idsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The images property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Images.ImagesRequestBuilder Images
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Images.ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keywords property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Keywords.KeywordsRequestBuilder Keywords
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Keywords.KeywordsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Lists.ListsRequestBuilder Lists
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rating property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Rating.RatingRequestBuilder Rating
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Rating.RatingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recommendations property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Recommendations.RecommendationsRequestBuilder Recommendations
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Recommendations.RecommendationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The release_dates property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Release_dates.Release_datesRequestBuilder Release_dates
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Release_dates.Release_datesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reviews property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Reviews.ReviewsRequestBuilder Reviews
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Reviews.ReviewsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The similar property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Similar.SimilarRequestBuilder Similar
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Similar.SimilarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The translations property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Translations.TranslationsRequestBuilder Translations
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Translations.TranslationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The videos property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Videos.VideosRequestBuilder Videos
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Videos.VideosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The watch property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Watch.WatchRequestBuilder Watch
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Item.Watch.WatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithMovie_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMovie_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/movie/{movie_id}{?append_to_response*,language*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithMovie_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMovie_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/movie/{movie_id}{?append_to_response*,language*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the top level details of a movie by ID.
        /// </summary>
        /// <returns>A <see cref="WithMovie_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_GetResponse?> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder.WithMovie_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_GetResponse> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder.WithMovie_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_GetResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_GetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the top level details of a movie by ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder.WithMovie_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder.WithMovie_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="WithMovie_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the top level details of a movie by ID.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithMovie_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>comma separated list of endpoints within this namespace, 20 items max</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("append_to_response")]
            public string? AppendToResponse { get; set; }
#nullable restore
#else
            [QueryParameter("append_to_response")]
            public string AppendToResponse { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("language")]
            public string? Language { get; set; }
#nullable restore
#else
            [QueryParameter("language")]
            public string Language { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
