// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Person.Changes;
using KozshTheMovieDbApi.v3.Person.Latest;
using KozshTheMovieDbApi.v3.Person.Popular;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using KozshTheMovieDbApi.v3.Person.Item;

namespace KozshTheMovieDbApi.v3.Person
{
    /// <summary>
    /// Builds and executes requests for operations under \3\person
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PersonRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changes property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Changes.ChangesRequestBuilder Changes
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Changes.ChangesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The latest property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Latest.LatestRequestBuilder Latest
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The popular property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Popular.PopularRequestBuilder Popular
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Popular.PopularRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the KozshTheMovieDbApi.v3.person.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithPerson_ItemRequestBuilder"/></returns>
        public global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("person_id", position);
                return new global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="PersonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/person", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="PersonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/person", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
