// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Account;
using KozshTheMovieDbApi.v3.Authentication;
using KozshTheMovieDbApi.v3.Certification;
using KozshTheMovieDbApi.v3.Collection;
using KozshTheMovieDbApi.v3.Company;
using KozshTheMovieDbApi.v3.Configuration;
using KozshTheMovieDbApi.v3.Credit;
using KozshTheMovieDbApi.v3.Discover;
using KozshTheMovieDbApi.v3.Find;
using KozshTheMovieDbApi.v3.Genre;
using KozshTheMovieDbApi.v3.Guest_session;
using KozshTheMovieDbApi.v3.Keyword;
using KozshTheMovieDbApi.v3.List;
using KozshTheMovieDbApi.v3.Movie;
using KozshTheMovieDbApi.v3.Network;
using KozshTheMovieDbApi.v3.Person;
using KozshTheMovieDbApi.v3.Review;
using KozshTheMovieDbApi.v3.Search;
using KozshTheMovieDbApi.v3.Trending;
using KozshTheMovieDbApi.v3.Tv;
using KozshTheMovieDbApi.v3.Watch;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KozshTheMovieDbApi.v3
{
    /// <summary>
    /// Builds and executes requests for operations under \3
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::KozshTheMovieDbApi.v3.Account.AccountRequestBuilder Account
        {
            get => new global::KozshTheMovieDbApi.v3.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The authentication property</summary>
        public global::KozshTheMovieDbApi.v3.Authentication.AuthenticationRequestBuilder Authentication
        {
            get => new global::KozshTheMovieDbApi.v3.Authentication.AuthenticationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The certification property</summary>
        public global::KozshTheMovieDbApi.v3.Certification.CertificationRequestBuilder Certification
        {
            get => new global::KozshTheMovieDbApi.v3.Certification.CertificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The collection property</summary>
        public global::KozshTheMovieDbApi.v3.Collection.CollectionRequestBuilder Collection
        {
            get => new global::KozshTheMovieDbApi.v3.Collection.CollectionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The company property</summary>
        public global::KozshTheMovieDbApi.v3.Company.CompanyRequestBuilder Company
        {
            get => new global::KozshTheMovieDbApi.v3.Company.CompanyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The configuration property</summary>
        public global::KozshTheMovieDbApi.v3.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::KozshTheMovieDbApi.v3.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credit property</summary>
        public global::KozshTheMovieDbApi.v3.Credit.CreditRequestBuilder Credit
        {
            get => new global::KozshTheMovieDbApi.v3.Credit.CreditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The discover property</summary>
        public global::KozshTheMovieDbApi.v3.Discover.DiscoverRequestBuilder Discover
        {
            get => new global::KozshTheMovieDbApi.v3.Discover.DiscoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The find property</summary>
        public global::KozshTheMovieDbApi.v3.Find.FindRequestBuilder Find
        {
            get => new global::KozshTheMovieDbApi.v3.Find.FindRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The genre property</summary>
        public global::KozshTheMovieDbApi.v3.Genre.GenreRequestBuilder Genre
        {
            get => new global::KozshTheMovieDbApi.v3.Genre.GenreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The guest_session property</summary>
        public global::KozshTheMovieDbApi.v3.Guest_session.Guest_sessionRequestBuilder Guest_session
        {
            get => new global::KozshTheMovieDbApi.v3.Guest_session.Guest_sessionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keyword property</summary>
        public global::KozshTheMovieDbApi.v3.Keyword.KeywordRequestBuilder Keyword
        {
            get => new global::KozshTheMovieDbApi.v3.Keyword.KeywordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::KozshTheMovieDbApi.v3.List.ListRequestBuilder List
        {
            get => new global::KozshTheMovieDbApi.v3.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The movie property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.MovieRequestBuilder Movie
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.MovieRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The network property</summary>
        public global::KozshTheMovieDbApi.v3.Network.NetworkRequestBuilder Network
        {
            get => new global::KozshTheMovieDbApi.v3.Network.NetworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The person property</summary>
        public global::KozshTheMovieDbApi.v3.Person.PersonRequestBuilder Person
        {
            get => new global::KozshTheMovieDbApi.v3.Person.PersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The review property</summary>
        public global::KozshTheMovieDbApi.v3.Review.ReviewRequestBuilder Review
        {
            get => new global::KozshTheMovieDbApi.v3.Review.ReviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::KozshTheMovieDbApi.v3.Search.SearchRequestBuilder Search
        {
            get => new global::KozshTheMovieDbApi.v3.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trending property</summary>
        public global::KozshTheMovieDbApi.v3.Trending.TrendingRequestBuilder Trending
        {
            get => new global::KozshTheMovieDbApi.v3.Trending.TrendingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tv property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.TvRequestBuilder Tv
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.TvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The watch property</summary>
        public global::KozshTheMovieDbApi.v3.Watch.WatchRequestBuilder Watch
        {
            get => new global::KozshTheMovieDbApi.v3.Watch.WatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
