// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using KozshTheMovieDbApi.v3.Trending.Tv.Item;

namespace KozshTheMovieDbApi.v3.Trending.Tv
{
    /// <summary>
    /// Builds and executes requests for operations under \3\trending\tv
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TvRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KozshTheMovieDbApi.v3.trending.tv.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithTime_windowItemRequestBuilder"/></returns>
        public global::KozshTheMovieDbApi.v3.Trending.Tv.Item.WithTime_windowItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("time_window", position);
                return new global::KozshTheMovieDbApi.v3.Trending.Tv.Item.WithTime_windowItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="TvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TvRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/trending/tv", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="TvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TvRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/trending/tv", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
