// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles
{
    /// <summary>
    /// Builds and executes requests for operations under \3\movie\{movie_id}\alternative_titles
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Alternative_titlesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="Alternative_titlesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Alternative_titlesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/movie/{movie_id}/alternative_titles{?country*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="Alternative_titlesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Alternative_titlesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/movie/{movie_id}/alternative_titles{?country*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the alternative titles for a movie.
        /// </summary>
        /// <returns>A <see cref="Alternative_titlesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesGetResponse?> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder.Alternative_titlesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesGetResponse> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder.Alternative_titlesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesGetResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the alternative titles for a movie.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder.Alternative_titlesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder.Alternative_titlesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="Alternative_titlesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Movie.Item.Alternative_titles.Alternative_titlesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the alternative titles for a movie.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Alternative_titlesRequestBuilderGetQueryParameters 
        {
            /// <summary>specify a ISO-3166-1 value to filter the results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("country")]
            public string? Country { get; set; }
#nullable restore
#else
            [QueryParameter("country")]
            public string Country { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
