// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Watch.Providers.Movie;
using KozshTheMovieDbApi.v3.Watch.Providers.Regions;
using KozshTheMovieDbApi.v3.Watch.Providers.Tv;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KozshTheMovieDbApi.v3.Watch.Providers
{
    /// <summary>
    /// Builds and executes requests for operations under \3\watch\providers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProvidersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The movie property</summary>
        public global::KozshTheMovieDbApi.v3.Watch.Providers.Movie.MovieRequestBuilder Movie
        {
            get => new global::KozshTheMovieDbApi.v3.Watch.Providers.Movie.MovieRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The regions property</summary>
        public global::KozshTheMovieDbApi.v3.Watch.Providers.Regions.RegionsRequestBuilder Regions
        {
            get => new global::KozshTheMovieDbApi.v3.Watch.Providers.Regions.RegionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tv property</summary>
        public global::KozshTheMovieDbApi.v3.Watch.Providers.Tv.TvRequestBuilder Tv
        {
            get => new global::KozshTheMovieDbApi.v3.Watch.Providers.Tv.TvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ProvidersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProvidersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/watch/providers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ProvidersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProvidersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/watch/providers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
