// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using KozshTheMovieDbApi.v3.Tv.Season.Item;

namespace KozshTheMovieDbApi.v3.Tv.Season
{
    /// <summary>
    /// Builds and executes requests for operations under \3\tv\season
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SeasonRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KozshTheMovieDbApi.v3.tv.season.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithSeason_ItemRequestBuilder"/></returns>
        public global::KozshTheMovieDbApi.v3.Tv.Season.Item.WithSeason_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("season_id", position);
                return new global::KozshTheMovieDbApi.v3.Tv.Season.Item.WithSeason_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="SeasonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeasonRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv/season", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="SeasonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeasonRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv/season", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
