// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Search.Collection;
using KozshTheMovieDbApi.v3.Search.Company;
using KozshTheMovieDbApi.v3.Search.Keyword;
using KozshTheMovieDbApi.v3.Search.Movie;
using KozshTheMovieDbApi.v3.Search.Multi;
using KozshTheMovieDbApi.v3.Search.Person;
using KozshTheMovieDbApi.v3.Search.Tv;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KozshTheMovieDbApi.v3.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \3\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The collection property</summary>
        public global::KozshTheMovieDbApi.v3.Search.Collection.CollectionRequestBuilder Collection
        {
            get => new global::KozshTheMovieDbApi.v3.Search.Collection.CollectionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The company property</summary>
        public global::KozshTheMovieDbApi.v3.Search.Company.CompanyRequestBuilder Company
        {
            get => new global::KozshTheMovieDbApi.v3.Search.Company.CompanyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keyword property</summary>
        public global::KozshTheMovieDbApi.v3.Search.Keyword.KeywordRequestBuilder Keyword
        {
            get => new global::KozshTheMovieDbApi.v3.Search.Keyword.KeywordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The movie property</summary>
        public global::KozshTheMovieDbApi.v3.Search.Movie.MovieRequestBuilder Movie
        {
            get => new global::KozshTheMovieDbApi.v3.Search.Movie.MovieRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multi property</summary>
        public global::KozshTheMovieDbApi.v3.Search.Multi.MultiRequestBuilder Multi
        {
            get => new global::KozshTheMovieDbApi.v3.Search.Multi.MultiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The person property</summary>
        public global::KozshTheMovieDbApi.v3.Search.Person.PersonRequestBuilder Person
        {
            get => new global::KozshTheMovieDbApi.v3.Search.Person.PersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tv property</summary>
        public global::KozshTheMovieDbApi.v3.Search.Tv.TvRequestBuilder Tv
        {
            get => new global::KozshTheMovieDbApi.v3.Search.Tv.TvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/search", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/search", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
