// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Person.Item.Changes;
using KozshTheMovieDbApi.v3.Person.Item.Combined_credits;
using KozshTheMovieDbApi.v3.Person.Item.External_ids;
using KozshTheMovieDbApi.v3.Person.Item.Images;
using KozshTheMovieDbApi.v3.Person.Item.Movie_credits;
using KozshTheMovieDbApi.v3.Person.Item.Tagged_images;
using KozshTheMovieDbApi.v3.Person.Item.Translations;
using KozshTheMovieDbApi.v3.Person.Item.Tv_credits;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Person.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \3\person\{person_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPerson_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changes property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.Changes.ChangesRequestBuilder Changes
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.Changes.ChangesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The combined_credits property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.Combined_credits.Combined_creditsRequestBuilder Combined_credits
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.Combined_credits.Combined_creditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The external_ids property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.External_ids.External_idsRequestBuilder External_ids
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.External_ids.External_idsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The images property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.Images.ImagesRequestBuilder Images
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.Images.ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The movie_credits property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.Movie_credits.Movie_creditsRequestBuilder Movie_credits
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.Movie_credits.Movie_creditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tagged_images property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.Tagged_images.Tagged_imagesRequestBuilder Tagged_images
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.Tagged_images.Tagged_imagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The translations property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.Translations.TranslationsRequestBuilder Translations
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.Translations.TranslationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tv_credits property</summary>
        public global::KozshTheMovieDbApi.v3.Person.Item.Tv_credits.Tv_creditsRequestBuilder Tv_credits
        {
            get => new global::KozshTheMovieDbApi.v3.Person.Item.Tv_credits.Tv_creditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithPerson_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPerson_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/person/{person_id}{?append_to_response*,language*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithPerson_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPerson_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/person/{person_id}{?append_to_response*,language*}", rawUrl)
        {
        }
        /// <summary>
        /// Query the top level details of a person.
        /// </summary>
        /// <returns>A <see cref="WithPerson_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_GetResponse?> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder.WithPerson_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_GetResponse> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder.WithPerson_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_GetResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_GetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Query the top level details of a person.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder.WithPerson_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder.WithPerson_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="WithPerson_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Person.Item.WithPerson_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Query the top level details of a person.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPerson_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>comma separated list of endpoints within this namespace, 20 items max</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("append_to_response")]
            public string? AppendToResponse { get; set; }
#nullable restore
#else
            [QueryParameter("append_to_response")]
            public string AppendToResponse { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("language")]
            public string? Language { get; set; }
#nullable restore
#else
            [QueryParameter("language")]
            public string Language { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
