// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Account.Item.Favorite;
using KozshTheMovieDbApi.v3.Account.Item.Lists;
using KozshTheMovieDbApi.v3.Account.Item.Rated;
using KozshTheMovieDbApi.v3.Account.Item.Watchlist;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Account.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \3\account\{account_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccount_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The favorite property</summary>
        public global::KozshTheMovieDbApi.v3.Account.Item.Favorite.FavoriteRequestBuilder Favorite
        {
            get => new global::KozshTheMovieDbApi.v3.Account.Item.Favorite.FavoriteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::KozshTheMovieDbApi.v3.Account.Item.Lists.ListsRequestBuilder Lists
        {
            get => new global::KozshTheMovieDbApi.v3.Account.Item.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rated property</summary>
        public global::KozshTheMovieDbApi.v3.Account.Item.Rated.RatedRequestBuilder Rated
        {
            get => new global::KozshTheMovieDbApi.v3.Account.Item.Rated.RatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The watchlist property</summary>
        public global::KozshTheMovieDbApi.v3.Account.Item.Watchlist.WatchlistRequestBuilder Watchlist
        {
            get => new global::KozshTheMovieDbApi.v3.Account.Item.Watchlist.WatchlistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithAccount_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccount_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/account/{account_id}{?session_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithAccount_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccount_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/account/{account_id}{?session_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the public details of an account on TMDB.
        /// </summary>
        /// <returns>A <see cref="WithAccount_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_GetResponse?> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_ItemRequestBuilder.WithAccount_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_GetResponse> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_ItemRequestBuilder.WithAccount_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_GetResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_GetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the public details of an account on TMDB.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_ItemRequestBuilder.WithAccount_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_ItemRequestBuilder.WithAccount_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="WithAccount_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Account.Item.WithAccount_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the public details of an account on TMDB.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithAccount_ItemRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("session_id")]
            public string? SessionId { get; set; }
#nullable restore
#else
            [QueryParameter("session_id")]
            public string SessionId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
