// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Trending.All;
using KozshTheMovieDbApi.v3.Trending.Movie;
using KozshTheMovieDbApi.v3.Trending.Person;
using KozshTheMovieDbApi.v3.Trending.Tv;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KozshTheMovieDbApi.v3.Trending
{
    /// <summary>
    /// Builds and executes requests for operations under \3\trending
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrendingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::KozshTheMovieDbApi.v3.Trending.All.AllRequestBuilder All
        {
            get => new global::KozshTheMovieDbApi.v3.Trending.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The movie property</summary>
        public global::KozshTheMovieDbApi.v3.Trending.Movie.MovieRequestBuilder Movie
        {
            get => new global::KozshTheMovieDbApi.v3.Trending.Movie.MovieRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The person property</summary>
        public global::KozshTheMovieDbApi.v3.Trending.Person.PersonRequestBuilder Person
        {
            get => new global::KozshTheMovieDbApi.v3.Trending.Person.PersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tv property</summary>
        public global::KozshTheMovieDbApi.v3.Trending.Tv.TvRequestBuilder Tv
        {
            get => new global::KozshTheMovieDbApi.v3.Trending.Tv.TvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="TrendingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrendingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/trending", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="TrendingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrendingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/trending", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
