// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using KozshTheMovieDbApi.v3.Keyword.Item;

namespace KozshTheMovieDbApi.v3.Keyword
{
    /// <summary>
    /// Builds and executes requests for operations under \3\keyword
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KeywordRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KozshTheMovieDbApi.v3.keyword.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithKeyword_ItemRequestBuilder"/></returns>
        public global::KozshTheMovieDbApi.v3.Keyword.Item.WithKeyword_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("keyword_id", position);
                return new global::KozshTheMovieDbApi.v3.Keyword.Item.WithKeyword_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KeywordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeywordRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/keyword", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KeywordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeywordRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/keyword", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
