// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Tv.On_the_air
{
    /// <summary>
    /// Builds and executes requests for operations under \3\tv\on_the_air
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class On_the_airRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="On_the_airRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public On_the_airRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv/on_the_air{?language*,page*,timezone*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="On_the_airRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public On_the_airRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv/on_the_air{?language*,page*,timezone*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of TV shows that air in the next 7 days.
        /// </summary>
        /// <returns>A <see cref="On_the_airGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airGetResponse?> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder.On_the_airRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airGetResponse> GetAsync(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder.On_the_airRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airGetResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of TV shows that air in the next 7 days.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder.On_the_airRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder.On_the_airRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="On_the_airRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a list of TV shows that air in the next 7 days.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class On_the_airRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("language")]
            public string? Language { get; set; }
#nullable restore
#else
            [QueryParameter("language")]
            public string Language { get; set; }
#endif
            [QueryParameter("page")]
            public int? Page { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("timezone")]
            public string? Timezone { get; set; }
#nullable restore
#else
            [QueryParameter("timezone")]
            public string Timezone { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
