// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Authentication.Session.ConvertNamespace;
using KozshTheMovieDbApi.v3.Authentication.Session.New;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KozshTheMovieDbApi.v3.Authentication.Session
{
    /// <summary>
    /// Builds and executes requests for operations under \3\authentication\session
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The convert property</summary>
        public global::KozshTheMovieDbApi.v3.Authentication.Session.ConvertNamespace.ConvertRequestBuilder Convert
        {
            get => new global::KozshTheMovieDbApi.v3.Authentication.Session.ConvertNamespace.ConvertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The new property</summary>
        public global::KozshTheMovieDbApi.v3.Authentication.Session.New.NewRequestBuilder New
        {
            get => new global::KozshTheMovieDbApi.v3.Authentication.Session.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="SessionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/authentication/session", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="SessionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/authentication/session", rawUrl)
        {
        }
        /// <summary>
        /// Delete Session
        /// </summary>
        /// <returns>A <see cref="SessionDeleteResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteResponse?> DeleteAsync(global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteResponse> DeleteAsync(global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteResponse>(requestInfo, global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::KozshTheMovieDbApi.v3.Authentication.Session.SessionDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="SessionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KozshTheMovieDbApi.v3.Authentication.Session.SessionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KozshTheMovieDbApi.v3.Authentication.Session.SessionRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
