// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Tv.Airing_today;
using KozshTheMovieDbApi.v3.Tv.Changes;
using KozshTheMovieDbApi.v3.Tv.Episode;
using KozshTheMovieDbApi.v3.Tv.Episode_group;
using KozshTheMovieDbApi.v3.Tv.Latest;
using KozshTheMovieDbApi.v3.Tv.On_the_air;
using KozshTheMovieDbApi.v3.Tv.Popular;
using KozshTheMovieDbApi.v3.Tv.Season;
using KozshTheMovieDbApi.v3.Tv.Top_rated;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using KozshTheMovieDbApi.v3.Tv.Item;

namespace KozshTheMovieDbApi.v3.Tv
{
    /// <summary>
    /// Builds and executes requests for operations under \3\tv
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TvRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The airing_today property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Airing_today.Airing_todayRequestBuilder Airing_today
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Airing_today.Airing_todayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The changes property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Changes.ChangesRequestBuilder Changes
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Changes.ChangesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episode property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Episode.EpisodeRequestBuilder Episode
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Episode.EpisodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episode_group property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Episode_group.Episode_groupRequestBuilder Episode_group
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Episode_group.Episode_groupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The latest property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Latest.LatestRequestBuilder Latest
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The on_the_air property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder On_the_air
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.On_the_air.On_the_airRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The popular property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Popular.PopularRequestBuilder Popular
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Popular.PopularRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The season property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Season.SeasonRequestBuilder Season
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Season.SeasonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The top_rated property</summary>
        public global::KozshTheMovieDbApi.v3.Tv.Top_rated.Top_ratedRequestBuilder Top_rated
        {
            get => new global::KozshTheMovieDbApi.v3.Tv.Top_rated.Top_ratedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the KozshTheMovieDbApi.v3.tv.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithSeries_ItemRequestBuilder"/></returns>
        public global::KozshTheMovieDbApi.v3.Tv.Item.WithSeries_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("series_id", position);
                return new global::KozshTheMovieDbApi.v3.Tv.Item.WithSeries_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="TvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TvRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="TvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TvRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/tv", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
