// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.v3.Movie.Changes;
using KozshTheMovieDbApi.v3.Movie.Latest;
using KozshTheMovieDbApi.v3.Movie.Now_playing;
using KozshTheMovieDbApi.v3.Movie.Popular;
using KozshTheMovieDbApi.v3.Movie.Top_rated;
using KozshTheMovieDbApi.v3.Movie.Upcoming;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using KozshTheMovieDbApi.v3.Movie.Item;

namespace KozshTheMovieDbApi.v3.Movie
{
    /// <summary>
    /// Builds and executes requests for operations under \3\movie
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MovieRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changes property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Changes.ChangesRequestBuilder Changes
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Changes.ChangesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The latest property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Latest.LatestRequestBuilder Latest
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The now_playing property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Now_playing.Now_playingRequestBuilder Now_playing
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Now_playing.Now_playingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The popular property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Popular.PopularRequestBuilder Popular
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Popular.PopularRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The top_rated property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Top_rated.Top_ratedRequestBuilder Top_rated
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Top_rated.Top_ratedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upcoming property</summary>
        public global::KozshTheMovieDbApi.v3.Movie.Upcoming.UpcomingRequestBuilder Upcoming
        {
            get => new global::KozshTheMovieDbApi.v3.Movie.Upcoming.UpcomingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the KozshTheMovieDbApi.v3.movie.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithMovie_ItemRequestBuilder"/></returns>
        public global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("movie_id", position);
                return new global::KozshTheMovieDbApi.v3.Movie.Item.WithMovie_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="MovieRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MovieRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/movie", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="MovieRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MovieRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/movie", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
