// <auto-generated/>
#pragma warning disable CS0618
using KozshTheMovieDbApi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KozshTheMovieDbApi.v3.Find.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithExternal_GetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The movie_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KozshTheMovieDbApi.Models.FindMovieResult>? MovieResults { get; set; }
#nullable restore
#else
        public List<global::KozshTheMovieDbApi.Models.FindMovieResult> MovieResults { get; set; }
#endif
        /// <summary>The person_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KozshTheMovieDbApi.Models.FindPersonResult>? PersonResults { get; set; }
#nullable restore
#else
        public List<global::KozshTheMovieDbApi.Models.FindPersonResult> PersonResults { get; set; }
#endif
        /// <summary>The tv_episode_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KozshTheMovieDbApi.Models.FindTvEpisodeResult>? TvEpisodeResults { get; set; }
#nullable restore
#else
        public List<global::KozshTheMovieDbApi.Models.FindTvEpisodeResult> TvEpisodeResults { get; set; }
#endif
        /// <summary>The tv_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KozshTheMovieDbApi.Models.FindTvResult>? TvResults { get; set; }
#nullable restore
#else
        public List<global::KozshTheMovieDbApi.Models.FindTvResult> TvResults { get; set; }
#endif
        /// <summary>The tv_season_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TvSeasonResults { get; set; }
#nullable restore
#else
        public UntypedNode TvSeasonResults { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="WithExternal_GetResponse"/> and sets the default values.
        /// </summary>
        public WithExternal_GetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="WithExternal_GetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KozshTheMovieDbApi.v3.Find.Item.WithExternal_GetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KozshTheMovieDbApi.v3.Find.Item.WithExternal_GetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "movie_results", n => { MovieResults = n.GetCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindMovieResult>(global::KozshTheMovieDbApi.Models.FindMovieResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "person_results", n => { PersonResults = n.GetCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindPersonResult>(global::KozshTheMovieDbApi.Models.FindPersonResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tv_episode_results", n => { TvEpisodeResults = n.GetCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindTvEpisodeResult>(global::KozshTheMovieDbApi.Models.FindTvEpisodeResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tv_results", n => { TvResults = n.GetCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindTvResult>(global::KozshTheMovieDbApi.Models.FindTvResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tv_season_results", n => { TvSeasonResults = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindMovieResult>("movie_results", MovieResults);
            writer.WriteCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindPersonResult>("person_results", PersonResults);
            writer.WriteCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindTvEpisodeResult>("tv_episode_results", TvEpisodeResults);
            writer.WriteCollectionOfObjectValues<global::KozshTheMovieDbApi.Models.FindTvResult>("tv_results", TvResults);
            writer.WriteObjectValue<UntypedNode>("tv_season_results", TvSeasonResults);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
